versions:
  "3.14.2":
    folder: all
  "3.14.0-rc3":
    folder: all
  "3.14.0-rc2":
    folder: all
  "3.13.11":
    folder: all
  "3.13.7":
    folder: all
  "3.13.1":
    folder: all
  "3.12.12":
    folder: all
  "3.12.11":
    folder: all
  "3.12.8":
    folder: all
  "3.11.14":
    folder: all
  "3.11.13":
    folder: all
  "3.11.11":
    folder: all
  "3.10.19":
    folder: all
  "3.10.18":
    folder: all
  "3.10.16":
    folder: all
  "3.9.25":
    folder: all
  "3.9.23":
    folder: all
  "3.9.21":
    folder: all
  "3.8.20":
    folder: all
