versions:
  "1.0.0-alpha.21":
    folder: all
  "1.0.0-alpha.20":
    folder: all
  "1.0.0-alpha.19":
    folder: all
  "1.0.0-alpha.18":
    folder: all
  "1.0.0-alpha.17":
    folder: all
  "1.0.0-alpha.16":
    folder: all
  "1.0.0-alpha.15":
    folder: all
  "1.0.0-alpha.14":
    folder: all
  "1.0.0-alpha.13":
    folder: all
  "1.0.0-alpha.12":
    folder: all
  "1.0.0-alpha.11":
    folder: all
  "1.0.0-alpha.10":
    folder: all
  "1.0.0-alpha.9":
    folder: all
  "1.0.0-alpha.8":
    folder: all
  "1.0.0-alpha.7":
    folder: all
  "1.0.0-alpha.6":
    folder: all
  "1.0.0-alpha.5":
    folder: all
  "1.0.0-alpha.4":
    folder: all
  "1.0.0-alpha.3":
    folder: all
  "1.0.0-alpha.2":
    folder: all
  "1.0.0-alpha.1":
    folder: all
